baseurl = "https://williamcook.dev"
languageCode = "en-us"
theme = "terminal"
pagination.pagerSize = 5

[params]
  contentTypeName = "content"
  themeColor = "pink"
  showMenuItems = 5
  fullWidthTheme = false
  centerTheme = true
  missingContentMessage = "This is not the page you're looking for."
  missingBackButtonLabel = "Back to About"
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[languages]
  [languages.en.params]
    title = "William George Cook"
    subtitle = "About me"
    keywords = "developer"
    copyright = "William George Cook 2024"

    [languages.en.params.logo]
      logoText = "William George Cook"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/"
      [[languages.en.menu.main]]
        identifier = "public_projects"
        name = "Public Projects"
        url = "/showcase"
      [[languages.en.menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "/contact"
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"